{% set version = "3.13.1" %}

package:
  name: libfuse
  version: {{ version }}

source:
  url: https://github.com/libfuse/libfuse/releases/download/fuse-{{ version }}/fuse-{{ version }}.tar.xz
  sha256: 6cd0759944c9aeb3d078b24a97b8a5cd5d49a0b8b7f15f85f32ac0c8a662fb6e
  patches:
    - 0001-Install-fusermount-init-script-into-sysconfdir.patch
    - 0002-Enable-building-utils-on-CentOS-6.patch

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    # Seems to be quite stable between minor versions
    # https://abi-laboratory.pro/?view=timeline&l=libfuse
    - {{ pin_subpackage('libfuse', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - meson
    - ninja
    - pkg-config
  host:
    - libiconv
  run:
    - libiconv

test:
  commands:
    - test -f ${PREFIX}/lib/libfuse3${SHLIB_EXT}
    - test -f ${PREFIX}/include/fuse3/fuse.h
    - 'mount.fuse3 2>&1 | grep -qF usage:'
    - ${PREFIX}/sbin/fusermount3 -V

about:
  home: https://github.com/libfuse/libfuse
  license: LGPL-2.1-only AND GPL-2.0-only
  license_file:
    - LICENSE
    - LGPL2.txt
    - GPL2.txt
  license_family: GPL
  summary: The reference implementation of the Linux FUSE (Filesystem in Userspace) interface

extra:
  recipe-maintainers:
    - asafkahlon
    - mbargull
    - xmnlab
