{% set version = "3.17.4" %}

package:
  name: libfuse
  version: {{ version }}

source:
  url: https://github.com/libfuse/libfuse/releases/download/fuse-{{ version }}/fuse-{{ version }}.tar.gz
  sha256: df9e40ae927b73dc702d0bce7925c0c618af47ad0b13204fbf2be66e54d8528b

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    # Seems to be quite stable between minor versions
    # https://abi-laboratory.pro/?view=timeline&l=libfuse
    - {{ pin_subpackage('libfuse', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - meson
    - ninja
    - pkg-config
  host:
    - libiconv
  run:
    - libiconv

test:
  commands:
    - test -f ${PREFIX}/lib/libfuse3${SHLIB_EXT}
    - test -f ${PREFIX}/include/fuse3/fuse.h
    - 'mount.fuse3 2>&1 | grep -qF usage:'
    - ${PREFIX}/sbin/fusermount3 -V
    - test -f ${PREFIX}/etc/init.d/fuse3
    - test -f ${PREFIX}/etc/fuse.conf

about:
  home: https://github.com/libfuse/libfuse
  license: LGPL-2.1-only AND GPL-2.0-only
  license_file:
    - LICENSE
    - LGPL2.txt
    - GPL2.txt
  license_family: GPL
  summary: The reference implementation of the Linux FUSE (Filesystem in Userspace) interface

extra:
  recipe-maintainers:
    - asafkahlon
    - mbargull
    - xmnlab
